### PR TITLE
Fixed and tested `SubStorage`

### LINKED ISSUE #351: List items of `SubStorage`
I found two problems with `SubStorage`:
1) Complete lack of tests
2) `list` operation does work correctly in some cases: when `SubStorage` is created with `Ket.ROOT` as prefix, `list` removes first met `/` symbol, thus returning not existing items. For example, if the sub storage contains `abc/xyz/hello.txt`, then list by `abc` key will return `abcxyz/hello.txt`

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #351 
Fixed problem with `list` operation of `SubStorage`, added some tests, todo for other tests.

The problem is described in the original issue:
> I found two problems with SubStorage:
> 1) Complete lack of tests
> 2) `list` operation does work correctly in some cases: when `SubStorage` is created with `Ket.ROOT` as prefix, list removes first met `/` symbol, thus returning not existing items. For example, if the sub storage contains `abc/xyz/hello.txt`, then list by `abc` key will return `abcxyz/hello.txt`
> 

The first problem is fixed by adding some tests (complete set of tests will be added later, by the `todo`), the second problem is fixed by correcting the regexp, used in `list` method.

### CODE REVIEW

**Comment by g4s8** [comment]
@olenagerasimova could you please describe what was the problem, and how did you fix it in PR?

**Comment by olenagerasimova** [comment]
@g4s8 done, the problems/bugs ets are supposed to described in the issues, do not they?

**Comment by olenagerasimova** [comment]
@g4s8 please, review, I need this fix to continue the work

**Comment by g4s8** [comment]
> @g4s8 done, the problems/bugs ets are supposed to described in the issues, do not they?

@olenagerasimova you are right, only solution is needed for PR

**Review by g4s8 — APPROVED** [review]
@olenagerasimova thanks

**Pull request merged**
