### PR TITLE
Add blocking wrapper over asto

### LINKED ISSUE #17: Add blocking wrapper over Storage

### PR DESCRIPTION
**Pull request by Sammers21**
fixes #17

### CODE REVIEW

**Comment by g4s8** [comment]
@Sammers21 why do we need these changes?

**Comment by Sammers21** [comment]
@g4s8, Storage interface is not easy to use. This wrapper makes it more simple.

**Comment by g4s8** [comment]
@Sammers21 I understand it, but do we have a use case for this adapter now?

**Comment by Sammers21** [comment]
@g4s8, of course, we, this could be used in a test

**Comment by Sammers21** [comment]
@rultor, release tag=`0.5.0`

**Pull request merged**
