### PR TITLE
Exclude fasterxml jackson databind from `vertx-rx-java2`

### PR DESCRIPTION
**Pull request by genryxy**
Part of #325

### CODE REVIEW

**Comment by genryxy** [comment]
@g4s8 sorry, I've just noticed that this dependency also excluded from asto in helm and conda, therefore it makes sense to exclude this dependency here

**Review by g4s8 — DISMISSED** [review]
@genryxy thanks. If you need a release, please add this change to the changelog.md file and create a tag with `git tag --annotate vM.m.b`, where M is a major version (same as previous in this case), m - minor (same too), and b - increment +1 from previous. And add description to tag annotation. Then push with `git push --tags origin`

**Comment by genryxy** [comment]
@g4s8 thanks, got it. Updated changelog

**Review by g4s8 — APPROVED** [review]
Approved. The tag should be made in merge commit in master branch

**Pull request merged**
