### PR TITLE
Aibolit style checker

### PR DESCRIPTION
**Pull request by acheshkov**
Aibolit style checker integrated to CI

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#209](https://github.com/artipie/asto/issues/209) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9e60269d-6cd4-4ec4-ad3d-291705211ddd); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/asto/issues/209#issuecomment-651122988))

@g4s8 The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#209](https://github.com/artipie/asto/issues/209), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/asto#209` is not assigned, can't get performer

**Pull request merged**
