### PR TITLE
Remove GCS package

### LINKED ISSUE #119: Google Storage support

### PR DESCRIPTION
**Pull request by Sammers21**
Since Google Cloud storage is s3 compatible, I would suggest removing underlying package for it.

Related to #119

### CODE REVIEW

**Comment by Sammers21** [comment]
@g4s8, all the information concerning this topic can be found at https://cloud.google.com/storage/docs/interoperability

**Comment by g4s8** [comment]
> @g4s8, all the information concerning this topic can be found at https://cloud.google.com/storage/docs/interoperability

@Sammers21 of course we have, but we need to extract only related information from there, so we won't need to find such information when working with Artipie storage.

**Comment by Sammers21** [comment]
@g4s8 ,what do you mean?

**Comment by g4s8** [comment]
@Sammers21 I mean that we need to keep related information in the documentation (readme) of this repo, such as how to configure the `Storage` to use google cloud

**Comment by Sammers21** [comment]
@g4s8, I can do it in a separated pull request

**Comment by g4s8** [comment]
@Sammers21 why? you are closing=solving the ticket and say that we don't need implementation of google storage implementation. So we need some documentation to be updated to close this ticket (like in one transaction)

**Comment by Sammers21** [comment]
@g4s8, ticket description has been updated

**Comment by 0crat** [comment]
Job `gh:artipie/asto#173` is not assigned, can't get performer

**Pull request merged**
