### PR TITLE
init prefixes

### PR DESCRIPTION
**Pull request by Guseyn**
Init prefixes for implementations of some interfaces

### CODE REVIEW

**Comment by g4s8** [comment]
@0crat assign @Vatavuk

**Comment by g4s8** [comment]
@Guseyn please add more details to PR description: what problem are you solving here and what's the problem of this PR (reason for changes)

**Comment by Guseyn** [comment]
@g4s8 done.

**Comment by Vatavuk** [comment]
@Guseyn you have merge confilcts

**Comment by Vatavuk** [comment]
@Guseyn please update the PR message. What are init prefixes? We are renaming storage classes to follow certain, more compact naming convention. Is that right?

**Comment by 0crat** [comment]
> @0crat assign @Vatavuk  ([here](https://github.com/artipie/asto/issues/115#issuecomment-599540331))

@g4s8 This pull request [#115](https://github.com/artipie/asto/issues/115) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ed83a530-decd-4c9d-8806-bafa1ec03157); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by Guseyn** [comment]
@Vatavuk I think this pr would take forever, as it will reequire also changes in different modules, so I am closing it.

**Comment by 0crat** [comment]
Job was finished in 11 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @vatavuk[/z](https://www.0crat.com/u/vatavuk)[/z](https://www.0crat.com/u/vatavuk) didn't make CR comments

**Comment by 0crat** [comment]
Pull request [#115](https://github.com/artipie/asto/issues/115) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
