### PR TITLE
#96 - Upload small content using put request in S3Storage even if siz…

### PR DESCRIPTION
**Pull request by olegmoz**
Part of #96 
Upload small content using put request in S3Storage even if size is unknown. Storage tries to read content up to some 10Mb, if content is bigger then multipart upload is used

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#123](https://github.com/artipie/asto/issues/123) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d522c0fa-e8eb-4df3-93e1-a3a422f19c79); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by Vatavuk** [comment]
@olegmoz how is this PR connected to refactoring of `MultipartUpload` class?

**Comment by Vatavuk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/asto/issues/123#issuecomment-603499616))

@Vatavuk The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#123](https://github.com/artipie/asto/issues/123), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/asto/issues/123#issuecomment-603499616))

@Vatavuk Job refused in 8 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by olegmoz** [comment]
@Vatavuk sorry, I messed up with issue number. Thank you for noticing. Will reopen PR

**Comment by 0crat** [comment]
Job `gh:artipie/asto#123` is not assigned, can't get performer

**Comment by 0crat** [comment]
Pull request [#123](https://github.com/artipie/asto/issues/123) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
