### PR TITLE
Fix windows builds

### PR DESCRIPTION
**Pull request by Sammers21**
* Vert.x instance is not created per each read/write opertaion
* @TempDir removed from Windows

related to #57

### CODE REVIEW

**Comment by paulodamaso** [comment]
@g4s8 assign me please

**Comment by g4s8** [comment]
@0crat assign @paulodamaso

**Comment by Sammers21** [comment]
@paulodamaso, the Pull Request does not touch test names. It is not a goal of this Pull Request

**Comment by 0crat** [comment]
> @0crat assign @paulodamaso  ([here](https://github.com/artipie/asto/issues/68#issuecomment-587440572))

@g4s8 This pull request [#68](https://github.com/artipie/asto/issues/68) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ae208094-0dc2-4b72-95f4-581d29ee8bcf); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by Sammers21** [comment]
@paulodamaso , pull request has been linked to a related ticket

**Comment by Sammers21** [comment]
@paulodamaso, review the pull request again

**Comment by Sammers21** [comment]
@paulodamaso, as it is being said, test names are not related to the pull request and will not discuss it with you because I'm not supposed to do it in the scope of this pull request.

**Comment by paulodamaso** [comment]
@Sammers21 I'm not discussing about the names with you, I'm asking you to change them

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by Sammers21** [comment]
> @Sammers21 I'm not discussing about the names with you, I'm asking you to change them

You are doing it in the wrong place.

**Comment by g4s8** [comment]
@paulodamaso @Sammers21 please discuss more respectfully and professionally, the goal of the code review is to improve the quality of code in PR, not to look like a winner in battle.

We don't review the code which is not in scope of current ticket. If we have some concerns about opinion based styles we can move it code style docs.

**Comment by paulodamaso** [comment]
@g4s8 I didn't any other complains about the code, you can merge

**Comment by 0crat** [comment]
Job was finished in 4 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by Sammers21** [comment]
@g4s8, can you release a new version, please?

**Comment by g4s8** [comment]
@rultor release, tag=`0.13.2`

**Pull request merged**
