### PR TITLE
move operation for google storage: #119

### PR DESCRIPTION
**Pull request by Guseyn**
move operation for google storage: #119

### CODE REVIEW

**Comment by paulodamaso** [comment]
@g4s8 Please assign me

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#125](https://github.com/artipie/asto/issues/125), see [§21](http://www.zerocracy.com/policy.html#21); @vatavuk[/z](https://www.0crat.com/u/vatavuk) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Job [#125](https://github.com/artipie/asto/issues/125) is not in the agenda of @vatavuk[/z](https://www.0crat.com/u/vatavuk), can't set title

**Comment by 0crat** [comment]
Job [#125](https://github.com/artipie/asto/issues/125) is not in the agenda of @vatavuk[/z](https://www.0crat.com/u/vatavuk), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (13 days), architects (@g4s8) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
Pull request [#125](https://github.com/artipie/asto/issues/125) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request closed without merging**
