### PR TITLE
Revert made changes with FileSystem + Vert.x 3.9.1 bump

### PR DESCRIPTION
**Pull request by Sammers21**
Reverted changes made in #172 + bump Vert.x version to 3.9.1

Before:
```
$ git clone https://github.com/Sammers21/asto.git && cd asto && git checkout rio_repeat_100
$ mvn clean install -Dtest=FileStorageTest#saveAndLoadHugeFiles
...
Run #0. Time: 1s860ms
Run #1. Time: 1s697ms
Run #2. Time: 1s393ms
Run #3. Time: 1s351ms
Run #4. Time: 1s151ms
Run #5. Time: 1s262ms
Run #6. Time: 1s76ms
Run #7. Time: 1s72ms
Run #8. Time: 1s46ms
Run #9. Time: 1s36ms
Run #10. Time: 1s50ms
Run #11. Time: 1s42ms
Run #12. Time: 1s46ms
Run #13. Time: 1s65ms
Run #14. Time: 1s55ms
Run #15. Time: 1s47ms
Run #16. Time: 1s50ms
Run #17. Time: 1s49ms
Run #18. Time: 1s47ms
Run #19. Time: 1s58ms
...
```

After:
```
$ git clone https://github.com/Sammers21/asto.git && cd asto && git checkout back_to_vertx_repeat_100
$ mvn clean install -Dtest=FileStorageTest#saveAndLoadHugeFiles
...
Run #0. Time: 1s799ms
Run #1. Time: 0s601ms
Run #2. Time: 0s589ms
Run #3. Time: 0s582ms
Run #4. Time: 0s602ms
Run #5. Time: 0s590ms
Run #6. Time: 0s583ms
Run #7. Time: 0s598ms
Run #8. Time: 0s580ms
Run #9. Time: 0s586ms
Run #10. Time: 0s589ms
Run #11. Time: 0s588ms
Run #12. Time: 0s582ms
Run #13. Time: 0s584ms
Run #14. Time: 0s589ms
Run #15. Time: 0s577ms
Run #16. Time: 0s594ms
Run #17. Time: 0s590ms
Run #18. Time: 0s583ms
Run #19. Time: 0s582ms
...
```

From the benchmark above It is clear that the previous version outperforming the existing one by ~50%

### CODE REVIEW

**Comment by Sammers21** [comment]
@g4s8, review the Pull Request please

**Comment by 0crat** [comment]
This pull request [#184](https://github.com/artipie/asto/issues/184) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/77db5fa3-5501-4e38-a4d5-d78ce3c77536); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@Sammers21 make sure you're running tests on correct commit before changes (I checked it again on `6b2e1e9b7b7ee99faaab91b3fc0ae31d5ba7145e` commit), see results:

Current fresh master:
scrot-2020-05-22-18:25:18

`6b2e1e9b7b7ee99faaab91b3fc0ae31d5ba7145e` commit:
scrot-2020-05-22-18:30:02

**Comment by Sammers21** [comment]
@g4s8, try the scripts I have provided

**Comment by g4s8** [comment]
@Sammers21 I don't know your branches in local repository, I'm comparing two commits in master

**Comment by Sammers21** [comment]
@g4s8, the only difference between master is the following: https://github.com/Sammers21/asto/commit/6baca488223b338e576074d6aac4e43edb359bec

The test is repeated 20 times and the time is measured. That is it.

**Comment by Sammers21** [comment]
@g4s8, does my results for the scripts are different on your machine?

**Comment by Sammers21** [comment]
@g4s8 , just replaced the save implementation with the vert.x based one. Now the difference is 50%

**Comment by Sammers21** [comment]
@g4s8, removed save replacement for this pull request, I guess I will do the replacement in #152, but the numbers still valid

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/asto/issues/184#issuecomment-633259516))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#184](https://github.com/artipie/asto/issues/184), please stop working. Reason for job resignation: Order was cancelled

**Comment by g4s8** [comment]
@Sammers21 I've just run your tests on my laptop ant the results are:
Latest vertx implementation from your branch
```
Run #1. Time: 0s495ms
Run #2. Time: 0s385ms
Run #3. Time: 0s389ms
Run #4. Time: 0s378ms
Run #5. Time: 0s389ms
Run #6. Time: 0s391ms
Run #7. Time: 0s380ms
Run #8. Time: 0s388ms
Run #9. Time: 0s398ms
Run #10. Time: 0s385ms
Run #11. Time: 0s389ms
Run #12. Time: 0s382ms
Run #13. Time: 0s384ms
Run #14. Time: 0s384ms
Run #15. Time: 0s382ms
Run #16. Time: 0s390ms
Run #17. Time: 0s391ms
Run #18. Time: 0s392ms
Run #19. Time: 0s387ms
```

Current implementation:
```
Run #0. Time: 0s749ms
Run #1. Time: 0s614ms
Run #2. Time: 0s542ms
Run #3. Time: 0s447ms
Run #4. Time: 0s426ms
Run #5. Time: 0s453ms
Run #6. Time: 0s439ms
Run #7. Time: 0s460ms
Run #8. Time: 0s486ms
Run #9. Time: 0s472ms
Run #10. Time: 0s449ms
Run #11. Time: 0s435ms
Run #12. Time: 0s452ms
Run #13. Time: 0s446ms
Run #14. Time: 0s454ms
Run #15. Time: 0s433ms
Run #16. Time: 0s431ms
Run #17. Time: 0s443ms
Run #18. Time: 0s438ms
Run #19. Time: 0s434ms
```

It doesn't seem to be 50% faster.

Just to compare the `dd` tool processes same amount of data in ~260ms:
```bash
dd if=/dev/zero of=/tmp/test.tmp bs=8192 count=131072
131072+0 records in
131072+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.261942 s, 4.1 GB/s
```

@Sammers21 what is your system buffer size? Can it be differed from standard 8K?

**Comment by Sammers21** [comment]
@g4s8, I have removed write replacement. It would be 50%with both of changes

**Comment by Sammers21** [comment]
> what is your system buffer size? Can it be differed from standard 8K?
@g4s8, No, it is 8kb

image

**Comment by Sammers21** [comment]
@g4s8, hello, any updates?

**Comment by g4s8** [comment]
> @g4s8, hello, any updates?

@Sammers21 I didn't check this issue yet. But I would try to avoid framework dependencies for core objects, like `Vertx` or `FileSystem` for `Storage` constructor.

**Comment by Sammers21** [comment]
@g4s8 , we had it before, what is wrong with it?

**Comment by g4s8** [comment]
> @g4s8 , we had it before, and you had nothing against it? What is different now?

@Sammers21 I didn't like this design before too, nothing changes. But it was an acceptable workaround for the beginning.

**Comment by g4s8** [comment]
@Sammers21 I'm closing this PR, since it's out of scope.

**Comment by 0crat** [comment]
Job `gh:artipie/asto#184` is not assigned, can't get performer

**Comment by Sammers21** [comment]
image

On a storage-optimised AWS instance **i3.large** running **Ubuntu 18.04**  the benchmarks results are the following:

**RIO**:
```
[INFO] Running com.artipie.asto.FileStorageTest
Run #0. Time: 1s605ms
Run #1. Time: 20s617ms
Run #2. Time: 20s515ms
Run #3. Time: 20s602ms
Run #4. Time: 20s428ms
Run #5. Time: 20s599ms
Run #6. Time: 20s376ms
Run #7. Time: 20s445ms
Run #8. Time: 20s332ms
Run #9. Time: 20s487ms
Run #10. Time: 20s441ms
Run #11. Time: 20s454ms
Run #12. Time: 20s335ms
Run #13. Time: 20s463ms
Run #14. Time: 20s444ms
Run #15. Time: 20s443ms
Run #16. Time: 20s435ms
Run #17. Time: 20s439ms
Run #18. Time: 20s305ms
Run #19. Time: 20s494ms
```

**Vert.x**:
```
Run #0. Time: 4s95ms
Run #1. Time: 2s228ms
Run #2. Time: 2s142ms
Run #3. Time: 2s119ms
Run #4. Time: 2s77ms
Run #5. Time: 2s157ms
Run #6. Time: 2s115ms
Run #7. Time: 2s124ms
Run #8. Time: 2s32ms
Run #9. Time: 2s40ms
Run #10. Time: 2s193ms
Run #11. Time: 2s101ms
Run #12. Time: 2s104ms
Run #13. Time: 2s122ms
Run #14. Time: 2s77ms
Run #15. Time: 2s158ms
Run #16. Time: 2s285ms
Run #17. Time: 2s210ms
Run #18. Time: 2s440ms
Run #19. Time: 2s524ms
```

**Comment by g4s8** [comment]
@Sammers21 @olegmoz I created benchmarks suite to compare rio vs Vertx in different aspects (read/write/copy), run it on EC2 machine and published results here: https://github.com/cqfn/rio/tree/master/benchmarks

I don't really believe that Vertx can be multiple times slower, I guess the root of performance issues is in asto implementation in `VertxRxFile` (which I copied as is to benchmark suite as Vertx API provider).

**Comment by olegmoz** [comment]
@Sammers21 could you please look into these benchmarks? Maybe you could point out what's wrong with Vert.x usage there? The numbers provided indicate that Vert.x is much slower and it makes one doubt that it is reasonable to migrate from existing `FileStorage` to new one is Artipie.

**Comment by Sammers21** [comment]
@olegmoz, эти бенчмарки не репрезентативны. Бенчмаркать нужно 2 имплементации FileStorage'a.

**Comment by Sammers21** [comment]
Собственно сам бенчмарк писал не я, а Кирилл. Я только добавил к нему цикл и замер временной. Результаты выше.

**Comment by olegmoz** [comment]
@Sammers21 I agree that we should better be testing `Storage` implementation, but these benchmark results make me concerned. So I'd like to repeat my question, could you please point out what is wrong with Vert.x usage in those benchmarks?

**Comment by g4s8** [comment]
@olegmoz I's a good idea to use asto primitives for benchmarks, so I replaced copy-paste from asto with `0.29` dependency and `VertxRxFile` usage, benchmark results are the same (on local machine, I don't think it will differ on EC2 instance). https://github.com/cqfn/rio/commit/ccee5469e1bb66c74cfb8575b6a79d9fe3c02a5a

**Comment by Sammers21** [comment]
@g4s8, ты сделал не то, что нужно. Сравни  пожалуйста две имплементации FileStorage'a.

**Comment by olegmoz** [comment]
@g4s8 thanks!
@Sammers21 could you explain what the difference it will make checking storages instead of "files"? `RxFile`/`VertxRxFile` do all the job for data copying, so they are expected to be bottlenecks. Aren't they?

**Comment by Sammers21** [comment]
@olegmoz, ну оперировать нужно каким-то эквивалентными еденицами, которые соответствуют определённой спецификации.

**Pull request closed without merging**
