### PR TITLE
#287 - Added FailedCompletionStage and it's usage

### LINKED ISSUE #287: Alternative for CompletableFuture.failedFuture
In Java 8 there is no quick way to create future that is failed from the start. It would be useful to create such class in ASTO and use it here and in other adapters

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #287 
Added `FailedCompletionStage` and it's usage

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@olegmoz qulice is complaining a lot, please fix it and I'll approve

**Comment by olegmoz** [comment]
@olenagerasimova sorry, fixed code style issues, please review

**Review by olenagerasimova — APPROVED** [review]
@olegmoz good to merge, thanks

**Comment by 0crat** [comment]
Job `gh:artipie/asto#288` is not assigned, can't get performer

**Pull request merged**
