### PR TITLE
delete operation for google storage: #119

### PR DESCRIPTION
**Pull request by Guseyn**
delete operation for google storage: #119

### CODE REVIEW

**Comment by paulodamaso** [comment]
@g4s8 Please assign me

**Comment by 0crat** [comment]
This pull request [#126](https://github.com/artipie/asto/issues/126) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/fa9ab895-1954-463d-941e-69a3b22cacfd); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by Vatavuk** [comment]
@Guseyn you have merge conflicts

**Comment by Vatavuk** [comment]
@Guseyn conflicts

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Vatavuk** [comment]
@Guseyn Same as for #122 I'm ok if you add a test in a separate PR just update the class.

**Comment by Vatavuk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/asto/issues/126#issuecomment-606673787))

@Vatavuk The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#126](https://github.com/artipie/asto/issues/126), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#126](https://github.com/artipie/asto/issues/126) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5d7ea90f-b708-448e-8d57-58a7d68e27b9); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by g4s8** [comment]
@Guseyn this PR is not ready

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/asto/issues/126#issuecomment-606753405))

@g4s8 The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#126](https://github.com/artipie/asto/issues/126), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/asto#126` is not assigned, can't get performer

**Comment by 0crat** [comment]
Pull request [#126](https://github.com/artipie/asto/issues/126) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
