### PR TITLE
Added unchecked scalars and test

### LINKED ISSUE #323: Add unchecked scalars
Let's add unchecked scalars implementations (I mean `Scalar` from cactoos) that will throw `ArtipieException` or `ArtipieIOException`.

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #323 
Added unchecked scalars `UncheckedScalar` and `UncheckedIOScalar` and test.

### CODE REVIEW

**Review by g4s8 — CHANGES_REQUESTED** [review]
@olenagerasimova I'm not sure if we need to add Cactoos as a compile-time dependency, since it has very unstable API, and previously we had many problems in Artipie with it because of frequently changes in interfaces and method signatures in Cactoos releases, such as `ClassNotFoundException` or `NoSuchMethodException`.

**Comment by olenagerasimova** [comment]
@g4s8 thanks, I see, `Scalar` is very convenient interface though, may we simply create one in `asto`?

**Comment by g4s8** [comment]
> @g4s8 thanks, I see, `Scalar` is very convenient interface though, may we simply create one in `asto`?

@olenagerasimova yes, we can take one stable version to source code

**Comment by olenagerasimova** [comment]
@g4s8 thanks, removed cactoos dependency, copied `Scalar` here

**Review by g4s8 — APPROVED** [review]
@olenagerasimova thanks

**Pull request merged**
