### PR TITLE
#87 - S3StorageTest refactoring

### PR DESCRIPTION
**Pull request by olegmoz**
Part of issue #87
Removed duplication of bucket creating code in S3Storage
S3StorageTest.shouldFailToSaveMultipartUploadWhenFailedToReadContent() generalized and moved to StorageSaveAndLoadTest.shouldFailToSaveErrorContent()
shouldNotExistForUnknownObject() removed as duplicate of StorageExistsTest.shouldNotExistForUnknownKey()

### CODE REVIEW

**Comment by paulodamaso** [comment]
@g4s8 I'm available, please assign me

**Comment by 0crat** [comment]
This pull request [#111](https://github.com/artipie/asto/issues/111) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f3e78310-8722-487d-9367-3764100113ea); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by fanifieiev** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/asto/issues/111#issuecomment-598817020))

@fanifieiev The user @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) resigned from [#111](https://github.com/artipie/asto/issues/111), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/asto/issues/111#issuecomment-598817020))

@fanifieiev Job refused in 6 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
This pull request [#111](https://github.com/artipie/asto/issues/111) is assigned to @dgarus[/z](https://www.0crat.com/u/dgarus), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/bbc7d810-e218-4b80-bf5a-d6a6709d0235); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by dgarus** [comment]
@g4s8 looks good to me

**Comment by g4s8** [comment]
@olegmoz please resolve merge conflicts

**Pull request merged**
