### PR TITLE
fix Concatenation performance issue

### PR DESCRIPTION
**Pull request by brastak**
For #191

Previous approach: create new Buffer for every new loaded chunk. New buffer size = previous buffer size + chunk size
New approach: keep the same Buffer between loads. When Buffer capacity is overflowed, new Buffer is created with capacity twice large as original

### CODE REVIEW

**Comment by brastak** [comment]
@olegmoz Please, take a look

**Comment by 0crat** [comment]
This pull request [#192](https://github.com/artipie/asto/issues/192) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/c911712b-bb29-4e2b-b287-972267b2ee78); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
This pull request [#192](https://github.com/artipie/asto/issues/192) is assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/a4e2a0ef-8b84-42b5-bced-31697aa3a92f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@brastak please add some description to this PR to explain how did you fix the problem

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by brastak** [comment]
@g4s8 added description

**Comment by brastak** [comment]
@olegmoz I have added test. I don't sure that we can check that concatenation is executed "fast". In the test I consider than if buffer size is grown by multiple 2, then it's ok. Real speed can be checked in the junit report

**Comment by olegmoz** [comment]
@g4s8 please merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@olegmoz please make sure you will find at least 3 issues during next CR, thanks

**Comment by sereshqua** [comment]
@olegmoz ping

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Pull request merged**
