### PR TITLE
#87 - Added S3Storage.exists() method implementation

### PR DESCRIPTION
**Pull request by olegmoz**
Part of #87 
Added S3Storage.exists() method implementation

### CODE REVIEW

**Comment by paulodamaso** [comment]
@g4s8 I'm available and in need of reviews, please assign me

**Comment by 0crat** [comment]
This pull request [#99](https://github.com/artipie/asto/issues/99) is assigned to @hdouss[/z](https://www.0crat.com/u/hdouss), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/665652a6-05be-4448-88c9-170f65d70b6b); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by HDouss** [comment]
@g4s8 Please review and/or merge

**Comment by HDouss** [comment]
@g4s8 ping

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR, performer @hdouss[/z](https://www.0crat.com/u/hdouss)[/z](https://www.0crat.com/u/hdouss) didn't make CR comments

**Pull request merged**
