### PR TITLE
test: add more tests for SubStorage

### LINKED ISSUE #369: Continue to add more tests for {@link SubStorage}. All the methods of the class should be...
The puzzle `352-ace2d56f` from #352 has to be resolved: 

https://github.com/artipie/asto/blob/aee483fca26b2506e3d3ed2d24f8ddbff97da4f8/src/test/java/com/artipie/asto/SubStorageTest.java#L20-L22

The puzzle was created by @baudoliver7 on 16-Nov-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by baudoliver7**
Add tests for `SubStorage` metadata and delete methods.

Close: #369

### CODE REVIEW

**Comment by baudoliver7** [comment]
@artipie/maintainers need a review here :)

**Review by olenagerasimova — APPROVED** [review]
@baudoliver7 thanks

**Comment by g4s8** [comment]
@baudoliver7 please add some details to PR description next time, it'll help to build good commit message in master branch. (I've fixed it by self this time)

**Comment by baudoliver7** [comment]
> @baudoliver7 please add some details to PR description next time, it'll help to build good commit message in master branch. (I've fixed it by self this time)

Got it. Thanks !

**Pull request merged**
