### PR TITLE
Updated versions plugin

### PR DESCRIPTION
**Pull request by g4s8**
#1 - updated versions plugin to `2.7`

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@g4s8 there is a bug in XML formatting

**Comment by g4s8** [comment]
@yegor256 should be fixed now: https://github.com/artipie/asto/pull/7/commits/d133b34adc43dfbfeaa6313dddcc1ef34a92fafc

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`

**Pull request merged**
